server:
  port: 9001

spring:
  datasource:
    username: ${database.username}
    password: ${database.password}
    url: ${database.url}
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_catalog: ${database.name}
        default_schema: ${database.schema}

database:
  url: jdbc:postgresql://postgres:5432/hotel
  schema: bookings
  username: bookings
  password: 123456
